name: 'Issue Label'
description: 'AI-powered issue labeling based on content analysis'
author: 'activadee'

inputs:
  model:
    description: 'Model to use for labeling'
    required: false
    default: 'anthropic/claude-haiku-4-5'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup OpenCode auth
      if: env.OPENCODE_AUTH != ''
      shell: bash
      run: |
        mkdir -p ~/.local/share/opencode
        echo "$OPENCODE_AUTH" > ~/.local/share/opencode/auth.json
    - name: Install opencode-ai
      shell: bash
      run: |
        curl -fsSL https://opencode.ai/install | bash
    - name: Install skill and tools
      shell: bash
      run: |
        mkdir -p .opencode/skill/issue-label
        cp "${{ github.action_path }}/skill.md" .opencode/skill/issue-label/SKILL.md
        mkdir -p ~/.config/opencode/tool
        cp "${{ github.action_path }}/../../.opencode/tool/"*.ts ~/.config/opencode/tool/

    - name: Label Issue
      shell: bash
      run: |
        opencode run --model "${{ inputs.model }}" \
          "Load the issue-label skill. Label issue ${{ github.event.issue.number }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
